### ISSUE TITLE
Harvester import error with pandalogger

### ISSUE THREAD

**Issue by mightqxc** [PanDAWMS/panda-common#41]
https://github.com/PanDAWMS/panda-common/blob/master/pandacommon/pandalogger/logger_config.py#L1
This breaks harvester with the following error:

```
Traceback (most recent call last):
  File "/opt/harvester/lib/python3.6/site-packages/pandaharvester/harvesterbody/master.py", line 18, in <module>
    from pandalogger import logger_config
  File "/opt/harvester/lib/python3.6/site-packages/pandacommon/pandalogger/logger_config.py", line 1, in <module>
    from ..commonconfig import common_config
ValueError: attempted relative import beyond top-level package
```

I am not sure where to fix. Probably in harvester as only harvester imports logger_config:

E.g. modify
https://github.com/HSF/harvester/blob/master/pandaharvester/harvesterbody/master.py#L18
to be
```
from pandacommon.pandalogger import logger_config
```
and also similar import lines of harvester code

**Comment by tmaeno** [comment]
I've added a change in 0.0.41

https://github.com/PanDAWMS/panda-common/commit/68a6a0ba3ded93a31ef88563e14b1a829be416cf

Does this help?

**Comment by mightqxc** [comment]
Yes, looks working. Thanks.
